In [43]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [44]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [45]:
df.shape

(569, 33)

In [46]:
df.drop(columns= ["id",'Unnamed: 32'], axis=1, inplace= True)

##Sepate data for Testing and Training

In [47]:
X = df.drop("diagnosis",axis=1)

In [48]:
y = df["diagnosis"]

In [49]:
X_train, X_test,y_train, y_test = train_test_split(X,y,test_size=0.2,random_state =42)

In [50]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
68,9.029,17.33,58.79,250.5,0.10660,0.14130,0.31300,0.04375,0.2111,0.08046,...,10.310,22.65,65.50,324.7,0.14820,0.43650,1.25200,0.17500,0.4228,0.11750
181,21.090,26.57,142.70,1311.0,0.11410,0.28320,0.24870,0.14960,0.2395,0.07398,...,26.680,33.48,176.50,2089.0,0.14910,0.75840,0.67800,0.29030,0.4098,0.12840
63,9.173,13.86,59.20,260.9,0.07721,0.08751,0.05988,0.02180,0.2341,0.06963,...,10.010,19.23,65.59,310.1,0.09836,0.16780,0.13970,0.05087,0.3282,0.08490
248,10.650,25.22,68.01,347.0,0.09657,0.07234,0.02379,0.01615,0.1897,0.06329,...,12.250,35.19,77.98,455.7,0.14990,0.13980,0.11250,0.06136,0.3409,0.08147
60,10.170,14.88,64.55,311.9,0.11340,0.08061,0.01084,0.01290,0.2743,0.06960,...,11.020,17.45,69.86,368.6,0.12750,0.09866,0.02168,0.02579,0.3557,0.08020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,8.888,14.64,58.79,244.0,0.09783,0.15310,0.08606,0.02872,0.1902,0.08980,...,9.733,15.67,62.56,284.4,0.12070,0.24360,0.14340,0.04786,0.2254,0.10840
106,11.640,18.33,75.17,412.5,0.11420,0.10170,0.07070,0.03485,0.1801,0.06520,...,13.140,29.26,85.51,521.7,0.16880,0.26600,0.28730,0.12180,0.2806,0.09097
270,14.290,16.82,90.30,632.6,0.06429,0.02675,0.00725,0.00625,0.1508,0.05376,...,14.910,20.65,94.44,684.6,0.08567,0.05036,0.03866,0.03333,0.2458,0.06120
435,13.980,19.62,91.12,599.5,0.10600,0.11330,0.11260,0.06463,0.1669,0.06544,...,17.040,30.80,113.90,869.3,0.16130,0.35680,0.40690,0.18270,0.3179,0.10550
102,12.180,20.52,77.22,458.7,0.08013,0.04038,0.02383,0.01770,0.1739,0.05677,...,13.340,32.84,84.58,547.8,0.11230,0.08862,0.11450,0.07431,0.2694,0.06878

In [51]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

##Scaling

In [52]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

##Encoding

In [53]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

##Numpy arrays to PyTorch tensors

In [54]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor  = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor  = torch.from_numpy(y_test)

In [55]:
type(X_train_tensor)

torch.Tensor

In [57]:
X_train.shape[1]

30

In [91]:
class Simple_NN() :

  def __init__(self,x):   #To initialize in one time
    self.weights = torch.rand(X_train.shape[1], 1, dtype=torch.float64, requires_grad = True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad = True)



  def forward_pass(self,X):

    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred


  def loss_function(self,y_pred,y):

     epsilon = 1e-7
     y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
     loss = -(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred)).mean()
     return loss

In [92]:
model = Simple_NN(X_train_tensor)

In [93]:
epoch = 25
learning_rate = 0.1

In [97]:
for i in range(epoch):

  #Forward Pass
  y_pred = model.forward_pass(X_train_tensor)

  #Loss Calculation
  loss= model.loss_function(y_pred,y_train_tensor)



  #Backward Pass
  loss.backward()

  #Parameters Update (W_new = W_old - lr*grad, b_new = b_old - lr*grad)
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #Gradient Zero:
  model.weights.grad.zero_()
  model.bias.grad.zero_()

 # print loss in each epoch
  print(f'Epoch: {i + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6805848481683385
Epoch: 2, Loss: 0.6802027210059322
Epoch: 3, Loss: 0.6798341856062045
Epoch: 4, Loss: 0.6794785451316044
Epoch: 5, Loss: 0.6791351470466473
Epoch: 6, Loss: 0.6788033798538607
Epoch: 7, Loss: 0.6784826700979754
Epoch: 8, Loss: 0.6781724796147119
Epoch: 9, Loss: 0.6778723030026651
Epoch: 10, Loss: 0.6775816652987356
Epoch: 11, Loss: 0.6773001198393382
Epoch: 12, Loss: 0.6770272462912287
Epoch: 13, Loss: 0.6767626488372641
Epoch: 14, Loss: 0.6765059545037446
Epoch: 15, Loss: 0.6762568116171987
Epoch: 16, Loss: 0.6760148883795736
Epoch: 17, Loss: 0.675779871551792
Epoch: 18, Loss: 0.6755514652365485
Epoch: 19, Loss: 0.6753293897520318
Epoch: 20, Loss: 0.675113380589017
Epoch: 21, Loss: 0.6749031874444392
Epoch: 22, Loss: 0.674698573325182
Epoch: 23, Loss: 0.6744993137163675
Epoch: 24, Loss: 0.674305195808939
Epoch: 25, Loss: 0.6741160177817882

In [99]:
y_pred = model.forward_pass(X_train_tensor)

In [101]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward_pass(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6228070259094238